### ISSUE TITLE
Animation not importing correctly 

### ISSUE THREAD

**Issue by italonvcc** [lmcintyre/AnimAssist#1]
Using max 2017 and the latest v1.13 import plugin.

![maxscene](https://user-images.githubusercontent.com/4566390/145660519-673ff2ef-4a86-46ce-9cb2-c5f29018177f.PNG)

Are you using a specific version of max/import tool?

**Comment by lmcintyre** [comment]
If you haven't figured this out, could you provide the skeleton and animation paths that you're trying to use?
