### ISSUE TITLE
Anim not... working?

### ISSUE THREAD

**Issue by jovemlex** [lmcintyre/AnimAssist#2]
I'm trying to convert a skeleton and a animation file to .hkx but I got this error everytime I try to run the code. 
Am I missing something? 

With the file "anim.py" on the folder:
![Screenshot_4](https://user-images.githubusercontent.com/36524530/147861406-752f64f8-f437-4aa1-840d-c4aae3a5ad8f.png)

Without the file "anim.py" on the folder:
![Screenshot_5](https://user-images.githubusercontent.com/36524530/147861427-6c756729-b2fb-4d96-bcdf-61d7417cc1d9.png)

**Comment by RkmXII** [comment]
Having the same problem with move.pap (this has the running/walking animations). The author said this script can't handle multiple animations but would be awesome if he/she could get it to work. Running animations are critical, being able to edit how the races run would be the best aesthetic change one could make in the game, as it's the animation we see the most in the game.

**Comment by Xecross** [comment]
That error is another cause, Python code's descriptive mistake.
4s = 4byte, I = 4byte(*5=20byte), 4I = 4*4=16byte, total 40byte, so "sklb_date[0:40]" is right.
I cope download sorce code, and correction it, and run anim.py.

**Comment by lmcintyre** [comment]
Thanks xecross. This specific issue is fixed in 1.0.1. It was minor so I just made another release.
