### ISSUE TITLE
Crash fixed - export settings

### ISSUE THREAD

**Issue by K3yw0rd** [lmcintyre/AnimAssist#3]
FFXIV was crashing when using an emote. **Solved by changing export toolset version to 2014** and disabling optimize tracks.
![INFO](https://user-images.githubusercontent.com/99110487/152668248-c79c40a4-813b-4c80-bd55-67e4605476ec.png)
Edited with 3DS max 2017
![test](https://user-images.githubusercontent.com/99110487/152668358-dbbca18a-32a7-4465-b976-074d75c67c98.png)

**Comment by lmcintyre** [comment]
Thanks for this. I made sure to emphasize the toolset version and made a note of the optimize tracks option.
